### ISSUE TITLE
DockbarX only runs under root

### ISSUE THREAD

**Issue by ACOdell** [M7S/dockbarx#21]
Pretty much what the title says. I can run "sudo dockx" and it runs like a charm, but when I run "dockx", this error is returned.
```
Traceback (most recent call last):
  File "/usr/bin/dockx", line 22, in <module>
    log_to_file()
  File "/usr/lib/pymodules/python2.7/dockbarx/log.py", line 32, in log_to_file
    file_handler = logging.handlers.RotatingFileHandler(log_file, "a", 0, 5)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/home/disgruntledlawyer/.dockbarx/log/dockbarx.log'
```
I'm running Linux Mint 17.2 XFCE currently and looking to use it with the XFCE plugin, if that's worth anything. I was also getting an error about Zeitgeist earlier, but that went away once I just installed it from the ppa.

Thanks!

**Comment by xuzhen** [comment]
run the following command to fix this problem
`sudo chown -R $USER:$USER ~/.dockbarx/`

**Comment by ACOdell** [comment]
That did the trick, thanks for helping me out!
