### ISSUE TITLE
Random occurence glitch in xfce4 after wake up from sleep

### ISSUE THREAD

**Issue by anggerbagus** [M7S/dockbarx#49]
In random occurence after wake from suspend, dockx doesn't render it self properly. it doesn't render the dock background and icon. but an icon will show up if the cursor hover above the coresponding icon.

dockx is standalone
ubuntu 16.04 using official ppa
xfce4.12 xubuntu
using 2 monitor and  2 dockx

**Comment by anggerbagus** [comment]
it happen if dockx initializing with Dock Type others than panel and if behaviour other than panel or standar, with a windows behind, or no need windows behind if behaviour is autohide. looks like the dockx was not yet finish it's initializing or there's something wrong with it's initialization then go hidden before it's done.

**Comment by anggerbagus** [comment]
![dockxbug](https://user-images.githubusercontent.com/8869999/32787464-29213bd4-c989-11e7-8f4f-d9ceff81023a.png)
it's looked like that on left side. note that only icon that was hovered/passed with cursor will appears. it's edited by the way, and the normal one should looked like the right side (4 icon on the right). the picture use plank background, but when the problem happens, any background theme will do (not rendered, like left side).

**Comment by M7S** [comment]
Sorry for not answering before now. Do you find any error messages in the log when this happens?

**Comment by thaewrapt** [comment]
Same here, standalone dockx + fluxbox as a window manager. I'll check my logs for something suspicious but my wild guess is that the standard autohide timeout of 200 is not enough to draw everything properly and then (for some reason) it ends all messed up after unhide.

**Comment by toshjp** [comment]
This issue has been left open without substantial updates for quite a while and I have the same problem on Zorin OS Lite 12.4 based on Ubuntu 16.04 (32bit) with Xfce 4.12. As far as I am aware, there is no sure way of reproducing the problem and no suspicions messages could be found in the log.

There is just one thing I noticed. When this happens, restarting dockx will be effective * only if * dockx does not overlap the active or foremost window at the restart. If it does overlap the active window and hide instantly, the problem persists even after the restart. I hope this might help.

**Comment by toshjp** [comment]
Since I installed the latest dockbarx packages from Xu Zhen's unofficial repository over pre-installed Zorin packages, the incorrect rendering problem seems to have gone. Perhaps, in my case, this issue only affects those packages included in Zorin OS Lite (dockbarx 0.92-1+zorin1, etc).

Or so had I thought for a while, for even after that the same problem recurred once (but only just once). The following is all I had got in the log:

INFO	| 2019-02-03 14:01:26,425	| DockbarX 0.93
INFO	| 2019-02-03 14:01:26,426	| DockbarX init
INFO	| 2019-02-03 14:01:27,075	| DockbarX reload
ERROR	| 2019-02-03 14:01:27,662	| /usr/bin/dockx:1195: GtkWarning: IA__gtk_window_get_screen: assertion 'GTK_IS_WINDOW (window)' failed
  screen = self.get_screen()
ERROR	| 2019-02-03 19:33:48,589	| Traceback (most recent call last):
ERROR	| 2019-02-03 19:33:48,599	|   File "/usr/lib/python2.7/dist-packages/dockbarx/groupbutton.py", line 466, in group_icon_changed
ERROR	| 2019-02-03 19:33:48,603	|     self.button.icon_factory.reset_icon()
ERROR	| 2019-02-03 19:33:48,604	| AttributeError: 'NoneType' object has no attribute 'reset_icon'
ERROR	| 2019-02-04 18:48:22,198	| Traceback (most recent call last):
ERROR	| 2019-02-04 18:48:22,209	|   File "/usr/lib/python2.7/dist-packages/dockbarx/groupbutton.py", line 466, in group_icon_changed
ERROR	| 2019-02-04 18:48:22,222	|     self.button.icon_factory.reset_icon()
ERROR	| 2019-02-04 18:48:22,224	| AttributeError: 'NoneType' object has no attribute 'reset_icon'

**Comment by toshjp** [comment]
Another update on my comments. Even after the installation of the latest dockbarx, the same problem still persists, though, apparently, errors occur less frequently.

INFO	| 2019-03-07 01:50:31,730	| DockbarX 0.93
INFO	| 2019-03-07 01:50:31,731	| DockbarX init
INFO	| 2019-03-07 01:50:36,353	| DockbarX reload
INFO	| 2019-03-07 01:54:53,754	| Executing: exo-open --launch TerminalEmulator
INFO	| 2019-03-07 01:54:58,251	| Executing: emacs-snapshot 
INFO	| 2019-03-07 02:01:08,412	| Executing: env LANG=ja_JP.UTF-8 firefox 
INFO	| 2019-03-07 02:35:16,990	| Executing: worker
INFO	| 2019-03-07 02:35:20,688	| Executing: libreoffice 
ERROR	| 2019-03-07 02:36:19,163	| Traceback (most recent call last):
ERROR	| 2019-03-07 02:36:19,178	|   File "/usr/lib/python2.7/dist-packages/dockbarx/groupbutton.py", line 466, in group_icon_changed
ERROR	| 2019-03-07 02:36:19,373	|     self.button.icon_factory.reset_icon()
ERROR	| 2019-03-07 02:36:19,384	| AttributeError: 'NoneType' object has no attribute 'reset_icon'

**Comment by xuzhen** [comment]
@toshjp I've uploaded a new version to my PPA for the 'AttributeError' issue.

**Comment by toshjp** [comment]
Thanks for your reply, xuzhen.

I installed the new version and since then have not encountered a single error for more than two days, even though I put my pc to sleep several times. Thanks very much.

**Comment by toshjp** [comment]
Unfortunately, even with the new version of dockbarx, the incorrect rendering problem has not been resolved yet. I have got a couple of rare errors like the following, always the same:

INFO	| 2019-03-18 12:01:16,646	| DockbarX 0.93
INFO	| 2019-03-18 12:01:16,646	| DockbarX init
INFO	| 2019-03-18 12:01:17,536	| DockbarX reload
ERROR	| 2019-03-18 12:01:18,213	| /usr/bin/dockx:1195: GtkWarning: IA__gtk_window_get_screen: assertion 'GTK_IS_WINDOW (window)' failed
  screen = self.get_screen()

**Comment by toshjp** [comment]
Thanks for uploading the new version. This is another update on my comments.

Just as I wrote in my first post, dockx is not rendered correctly if it overlaps the active window at startup and hides instantly. But once it has been rendered correctly at startup, it runs pretty smoothly even though I put my pc to sleep on and off.

Another problem I noticed a couple of days ago. When I create a launcher for a Wine program by drag-and-dropping the menu icon to dockx, it does not work, the launcher fails to start the program. I thought this worked before or am I just missing something?
