### ISSUE TITLE
dockbarx gtk3 help

### ISSUE THREAD

**Issue by slava8686** [M7S/dockbarx#62]
DockbarX 0.93-gtk3
DockbarX init
DockbarX reload
Traceback (most recent call last):
  File "/usr/bin/dockx", line 1462, in <module>
    dockx = DockX(monitor)
  File "/usr/bin/dockx", line 504, in __init__
    self.dockbar.load()
  File "/usr/lib/python2.7/site-packages/dockbarx/dockbar.py", line 567, in load
    self.reload(tell_parent=False)
  File "/usr/lib/python2.7/site-packages/dockbarx/dockbar.py", line 644, in reload
    self.__on_window_opened(self.screen, window)
  File "/usr/lib/python2.7/site-packages/dockbarx/dockbar.py", line 836, in __on_window_opened
    self.__add_window(window)
  File "/usr/lib/python2.7/site-packages/dockbarx/dockbar.py", line 1013, in __add_window
    window=window)
  File "/usr/lib/python2.7/site-packages/dockbarx/dockbar.py", line 904, in __make_groupbutton
    group = Group(self, identifier, desktop_entry, pinned, self.size)
  File "/usr/lib/python2.7/site-packages/dockbarx/groupbutton.py", line 178, in __init__
    self.button = GroupButton(self, size)
  File "/usr/lib/python2.7/site-packages/dockbarx/groupbutton.py", line 1435, in __init__
    self.drag_source_set_icon_pixbuf(self.icon_factory.get_icon(32))
  File "/usr/lib/python2.7/site-packages/dockbarx/iconfactory.py", line 133, in get_icon
    return self.__find_icon_pixbuf(size)
  File "/usr/lib/python2.7/site-packages/dockbarx/iconfactory.py", line 558, in __find_icon_pixbuf
    pixbuf = GdkPixbuf.Pixbuf(GdkPixbuf.Colorspace.RGB, True, 8, size,size)
TypeError: GObject.__init__() takes exactly 0 arguments (5 given)

**Comment by xuzhen** [comment]
edit /usr/lib/python2.7/site-packages/dockbarx/iconfactory.py, change line 558 from
`pixbuf = GdkPixbuf.Pixbuf(GdkPixbuf.Colorspace.RGB, True, 8, size,size)`
to
`pixbuf = GdkPixbuf.Pixbuf.new(GdkPixbuf.Colorspace.RGB, True, 8, size,size)`

You can use the following command in shell
`sudo sed -i '558s/GdkPixbuf.Pixbuf/GdkPixbuf.Pixbuf.new/' /usr/local/lib/python2.7/dist-packages/dockbarx/iconfactory.py`
