### ISSUE TITLE
Can not run dockx with binding failed.

### ISSUE THREAD

**Issue by kmvan** [M7S/dockbarx#80]
Thanks your work.

DE: xfce v4.13

```
$ dockx 
DockbarX 0.93
DockbarX init

** (dockx:6078): WARNING **: 12:48:00.628: Binding '<super>0' failed!

** (dockx:6078): WARNING **: 12:48:00.628: Binding '<super>1' failed!

** (dockx:6078): WARNING **: 12:48:00.628: Binding '<super>2' failed!

** (dockx:6078): WARNING **: 12:48:00.628: Binding '<super>3' failed!

** (dockx:6078): WARNING **: 12:48:00.628: Binding '<super>4' failed!

** (dockx:6078): WARNING **: 12:48:00.629: Binding '<super>5' failed!

** (dockx:6078): WARNING **: 12:48:00.629: Binding '<super>6' failed!

** (dockx:6078): WARNING **: 12:48:00.629: Binding '<super>7' failed!

** (dockx:6078): WARNING **: 12:48:00.629: Binding '<super>8' failed!

** (dockx:6078): WARNING **: 12:48:00.629: Binding '<super>9' failed!
DockbarX reload
Traceback (most recent call last):
  File "/usr/bin/dockx", line 1439, in <module>
    dockx = DockX(monitor)
  File "/usr/bin/dockx", line 508, in __init__
    self.dockbar.load()
  File "/usr/lib/python2.7/site-packages/dockbarx/dockbar.py", line 552, in load
    self.reload(tell_parent=False)
  File "/usr/lib/python2.7/site-packages/dockbarx/dockbar.py", line 628, in reload
    self.__on_window_opened(self.screen, window)
  File "/usr/lib/python2.7/site-packages/dockbarx/dockbar.py", line 815, in __on_window_opened
    self.__add_window(window)
  File "/usr/lib/python2.7/site-packages/dockbarx/dockbar.py", line 915, in __add_window
    f = open("/proc/"+str(pid)+"/cmdline", "r")
IOError: [Errno 2] No such file or directory: '/proc/0/cmdline'
```

Any tip?

**Comment by xuzhen** [comment]
Can you provide the output of ```xwininfo -root -tree``` when this error happens?
It seems that there is a window with no name nor pid.

**Comment by xuzhen** [comment]
Should be fixed now. Before the patch being merged, you can try [my fork](https://github.com/xuzhen/dockbarx/) or [my PPA](https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx/+packages)
