### ISSUE TITLE
Failed to compile .po files with python3

### ISSUE THREAD

**Issue by xuzhen** [M7S/dockbarx#97]
```
Compiling po/zh_TW.po for dockbarx
Traceback (most recent call last):
  File "setup.py", line 152, in <module>
    cmdclass=cmdclass
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
    self.run_command('build')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 68, in run
    _build.run(self)
  File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 57, in run
    msgfmt.make(src, dest)
  File "/tmp/dockbarx-pygi-python3/msgfmt.py", line 177, in make
    output = generate()
  File "/tmp/dockbarx-pygi-python3/msgfmt.py", line 93, in generate
    output += ids
TypeError: can't concat str to bytes
```

**Comment by xuzhen** [comment]
The commit https://github.com/M7S/dockbarx/commit/f73fecd1b1b6d44e3349db1e6075c8c3765443ec is NOT a proper way to fix this issue.
The program will crash when not using en_US
```
Traceback (most recent call last):
  File "/usr/bin/dockx", line 32, in <module>
    import dockbarx.dockbar
  File "/usr/lib/python3/dist-packages/dockbarx/dockbar.py", line 30, in <module>
    from . import cairowidgets
  File "/usr/lib/python3/dist-packages/dockbarx/cairowidgets.py", line 35, in <module>
    from .theme import PopupStyle
  File "/usr/lib/python3/dist-packages/dockbarx/theme.py", line 33, in <module>
    from . import i18n
  File "/usr/lib/python3/dist-packages/dockbarx/i18n.py", line 26, in <module>
    fallback = True)
  File "/usr/lib/python3.7/gettext.py", line 548, in translation
    t = _translations.setdefault(key, class_(fp))
  File "/usr/lib/python3.7/gettext.py", line 260, in __init__
    self._parse(fp)
  File "/usr/lib/python3.7/gettext.py", line 421, in _parse
    catalog[str(msg, charset)] = str(tmsg, charset)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
Exception ignored in: <dockbarx.log.StdOutWrapper object at 0x7fa08cadea50>
AttributeError: 'StdOutWrapper' object has no attribute 'flush'```

**Comment by M7S** [comment]
That was a nice solution. Thanks!
